<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\Models\Country;
use App\Models\Division;
use App\Models\District;
use App\Models\Upazila;

class AddressSeeder extends Seeder
{
	
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date = Carbon::now();
        \DB::table('countries')->delete();

		$countries = array(
			array('code' => 'US', 'name' => 'United States'),
			array('code' => 'CA', 'name' => 'Canada'),
			array('code' => 'AF', 'name' => 'Afghanistan'),
			array('code' => 'AL', 'name' => 'Albania'),
			array('code' => 'DZ', 'name' => 'Algeria'),
			array('code' => 'AS', 'name' => 'American Samoa'),
			array('code' => 'AD', 'name' => 'Andorra'),
			array('code' => 'AO', 'name' => 'Angola'),
			array('code' => 'AI', 'name' => 'Anguilla'),
			array('code' => 'AQ', 'name' => 'Antarctica'),
			array('code' => 'AG', 'name' => 'Antigua and/or Barbuda'),
			array('code' => 'AR', 'name' => 'Argentina'),
			array('code' => 'AM', 'name' => 'Armenia'),
			array('code' => 'AW', 'name' => 'Aruba'),
			array('code' => 'AU', 'name' => 'Australia'),
			array('code' => 'AT', 'name' => 'Austria'),
			array('code' => 'AZ', 'name' => 'Azerbaijan'),
			array('code' => 'BS', 'name' => 'Bahamas'),
			array('code' => 'BH', 'name' => 'Bahrain'),
			array('code' => 'BD', 'name' => 'Bangladesh'),
			array('code' => 'BB', 'name' => 'Barbados'),
			array('code' => 'BY', 'name' => 'Belarus'),
			array('code' => 'BE', 'name' => 'Belgium'),
			array('code' => 'BZ', 'name' => 'Belize'),
			array('code' => 'BJ', 'name' => 'Benin'),
			array('code' => 'BM', 'name' => 'Bermuda'),
			array('code' => 'BT', 'name' => 'Bhutan'),
			array('code' => 'BO', 'name' => 'Bolivia'),
			array('code' => 'BA', 'name' => 'Bosnia and Herzegovina'),
			array('code' => 'BW', 'name' => 'Botswana'),
			array('code' => 'BV', 'name' => 'Bouvet Island'),
			array('code' => 'BR', 'name' => 'Brazil'),
			array('code' => 'IO', 'name' => 'British lndian Ocean Territory'),
			array('code' => 'BN', 'name' => 'Brunei Darussalam'),
			array('code' => 'BG', 'name' => 'Bulgaria'),
			array('code' => 'BF', 'name' => 'Burkina Faso'),
			array('code' => 'BI', 'name' => 'Burundi'),
			array('code' => 'KH', 'name' => 'Cambodia'),
			array('code' => 'CM', 'name' => 'Cameroon'),
			array('code' => 'CV', 'name' => 'Cape Verde'),
			array('code' => 'KY', 'name' => 'Cayman Islands'),
			array('code' => 'CF', 'name' => 'Central African Republic'),
			array('code' => 'TD', 'name' => 'Chad'),
			array('code' => 'CL', 'name' => 'Chile'),
			array('code' => 'CN', 'name' => 'China'),
			array('code' => 'CX', 'name' => 'Christmas Island'),
			array('code' => 'CC', 'name' => 'Cocos (Keeling) Islands'),
			array('code' => 'CO', 'name' => 'Colombia'),
			array('code' => 'KM', 'name' => 'Comoros'),
			array('code' => 'CG', 'name' => 'Congo'),
			array('code' => 'CK', 'name' => 'Cook Islands'),
			array('code' => 'CR', 'name' => 'Costa Rica'),
			array('code' => 'HR', 'name' => 'Croatia (Hrvatska)'),
			array('code' => 'CU', 'name' => 'Cuba'),
			array('code' => 'CY', 'name' => 'Cyprus'),
			array('code' => 'CZ', 'name' => 'Czech Republic'),
			array('code' => 'CD', 'name' => 'Democratic Republic of Congo'),
			array('code' => 'DK', 'name' => 'Denmark'),
			array('code' => 'DJ', 'name' => 'Djibouti'),
			array('code' => 'DM', 'name' => 'Dominica'),
			array('code' => 'DO', 'name' => 'Dominican Republic'),
			array('code' => 'TP', 'name' => 'East Timor'),
			array('code' => 'EC', 'name' => 'Ecudaor'),
			array('code' => 'EG', 'name' => 'Egypt'),
			array('code' => 'SV', 'name' => 'El Salvador'),
			array('code' => 'GQ', 'name' => 'Equatorial Guinea'),
			array('code' => 'ER', 'name' => 'Eritrea'),
			array('code' => 'EE', 'name' => 'Estonia'),
			array('code' => 'ET', 'name' => 'Ethiopia'),
			array('code' => 'FK', 'name' => 'Falkland Islands (Malvinas)'),
			array('code' => 'FO', 'name' => 'Faroe Islands'),
			array('code' => 'FJ', 'name' => 'Fiji'),
			array('code' => 'FI', 'name' => 'Finland'),
			array('code' => 'FR', 'name' => 'France'),
			array('code' => 'FX', 'name' => 'France, Metropolitan'),
			array('code' => 'GF', 'name' => 'French Guiana'),
			array('code' => 'PF', 'name' => 'French Polynesia'),
			array('code' => 'TF', 'name' => 'French Southern Territories'),
			array('code' => 'GA', 'name' => 'Gabon'),
			array('code' => 'GM', 'name' => 'Gambia'),
			array('code' => 'GE', 'name' => 'Georgia'),
			array('code' => 'DE', 'name' => 'Germany'),
			array('code' => 'GH', 'name' => 'Ghana'),
			array('code' => 'GI', 'name' => 'Gibraltar'),
			array('code' => 'GR', 'name' => 'Greece'),
			array('code' => 'GL', 'name' => 'Greenland'),
			array('code' => 'GD', 'name' => 'Grenada'),
			array('code' => 'GP', 'name' => 'Guadeloupe'),
			array('code' => 'GU', 'name' => 'Guam'),
			array('code' => 'GT', 'name' => 'Guatemala'),
			array('code' => 'GN', 'name' => 'Guinea'),
			array('code' => 'GW', 'name' => 'Guinea-Bissau'),
			array('code' => 'GY', 'name' => 'Guyana'),
			array('code' => 'HT', 'name' => 'Haiti'),
			array('code' => 'HM', 'name' => 'Heard and Mc Donald Islands'),
			array('code' => 'HN', 'name' => 'Honduras'),
			array('code' => 'HK', 'name' => 'Hong Kong'),
			array('code' => 'HU', 'name' => 'Hungary'),
			array('code' => 'IS', 'name' => 'Iceland'),
			array('code' => 'IN', 'name' => 'India'),
			array('code' => 'ID', 'name' => 'Indonesia'),
			array('code' => 'IR', 'name' => 'Iran (Islamic Republic of)'),
			array('code' => 'IQ', 'name' => 'Iraq'),
			array('code' => 'IE', 'name' => 'Ireland'),
			array('code' => 'IL', 'name' => 'Israel'),
			array('code' => 'IT', 'name' => 'Italy'),
			array('code' => 'CI', 'name' => 'Ivory Coast'),
			array('code' => 'JM', 'name' => 'Jamaica'),
			array('code' => 'JP', 'name' => 'Japan'),
			array('code' => 'JO', 'name' => 'Jordan'),
			array('code' => 'KZ', 'name' => 'Kazakhstan'),
			array('code' => 'KE', 'name' => 'Kenya'),
			array('code' => 'KI', 'name' => 'Kiribati'),
			array('code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of'),
			array('code' => 'KR', 'name' => 'Korea, Republic of'),
			array('code' => 'KW', 'name' => 'Kuwait'),
			array('code' => 'KG', 'name' => 'Kyrgyzstan'),
			array('code' => 'LA', 'name' => 'Lao People\'s Democratic Republic'),
			array('code' => 'LV', 'name' => 'Latvia'),
			array('code' => 'LB', 'name' => 'Lebanon'),
			array('code' => 'LS', 'name' => 'Lesotho'),
			array('code' => 'LR', 'name' => 'Liberia'),
			array('code' => 'LY', 'name' => 'Libyan Arab Jamahiriya'),
			array('code' => 'LI', 'name' => 'Liechtenstein'),
			array('code' => 'LT', 'name' => 'Lithuania'),
			array('code' => 'LU', 'name' => 'Luxembourg'),
			array('code' => 'MO', 'name' => 'Macau'),
			array('code' => 'MK', 'name' => 'Macedonia'),
			array('code' => 'MG', 'name' => 'Madagascar'),
			array('code' => 'MW', 'name' => 'Malawi'),
			array('code' => 'MY', 'name' => 'Malaysia'),
			array('code' => 'MV', 'name' => 'Maldives'),
			array('code' => 'ML', 'name' => 'Mali'),
			array('code' => 'MT', 'name' => 'Malta'),
			array('code' => 'MH', 'name' => 'Marshall Islands'),
			array('code' => 'MQ', 'name' => 'Martinique'),
			array('code' => 'MR', 'name' => 'Mauritania'),
			array('code' => 'MU', 'name' => 'Mauritius'),
			array('code' => 'TY', 'name' => 'Mayotte'),
			array('code' => 'MX', 'name' => 'Mexico'),
			array('code' => 'FM', 'name' => 'Micronesia, Federated States of'),
			array('code' => 'MD', 'name' => 'Moldova, Republic of'),
			array('code' => 'MC', 'name' => 'Monaco'),
			array('code' => 'MN', 'name' => 'Mongolia'),
			array('code' => 'MS', 'name' => 'Montserrat'),
			array('code' => 'MA', 'name' => 'Morocco'),
			array('code' => 'MZ', 'name' => 'Mozambique'),
			array('code' => 'MM', 'name' => 'Myanmar'),
			array('code' => 'NA', 'name' => 'Namibia'),
			array('code' => 'NR', 'name' => 'Nauru'),
			array('code' => 'NP', 'name' => 'Nepal'),
			array('code' => 'NL', 'name' => 'Netherlands'),
			array('code' => 'AN', 'name' => 'Netherlands Antilles'),
			array('code' => 'NC', 'name' => 'New Caledonia'),
			array('code' => 'NZ', 'name' => 'New Zealand'),
			array('code' => 'NI', 'name' => 'Nicaragua'),
			array('code' => 'NE', 'name' => 'Niger'),
			array('code' => 'NG', 'name' => 'Nigeria'),
			array('code' => 'NU', 'name' => 'Niue'),
			array('code' => 'NF', 'name' => 'Norfork Island'),
			array('code' => 'MP', 'name' => 'Northern Mariana Islands'),
			array('code' => 'NO', 'name' => 'Norway'),
			array('code' => 'OM', 'name' => 'Oman'),
			array('code' => 'PK', 'name' => 'Pakistan'),
			array('code' => 'PW', 'name' => 'Palau'),
			array('code' => 'PA', 'name' => 'Panama'),
			array('code' => 'PG', 'name' => 'Papua New Guinea'),
			array('code' => 'PY', 'name' => 'Paraguay'),
			array('code' => 'PE', 'name' => 'Peru'),
			array('code' => 'PH', 'name' => 'Philippines'),
			array('code' => 'PN', 'name' => 'Pitcairn'),
			array('code' => 'PL', 'name' => 'Poland'),
			array('code' => 'PT', 'name' => 'Portugal'),
			array('code' => 'PR', 'name' => 'Puerto Rico'),
			array('code' => 'QA', 'name' => 'Qatar'),
			array('code' => 'SS', 'name' => 'Republic of South Sudan'),
			array('code' => 'RE', 'name' => 'Reunion'),
			array('code' => 'RO', 'name' => 'Romania'),
			array('code' => 'RU', 'name' => 'Russian Federation'),
			array('code' => 'RW', 'name' => 'Rwanda'),
			array('code' => 'KN', 'name' => 'Saint Kitts and Nevis'),
			array('code' => 'LC', 'name' => 'Saint Lucia'),
			array('code' => 'VC', 'name' => 'Saint Vincent and the Grenadines'),
			array('code' => 'WS', 'name' => 'Samoa'),
			array('code' => 'SM', 'name' => 'San Marino'),
			array('code' => 'ST', 'name' => 'Sao Tome and Principe'),
			array('code' => 'SA', 'name' => 'Saudi Arabia'),
			array('code' => 'SN', 'name' => 'Senegal'),
			array('code' => 'RS', 'name' => 'Serbia'),
			array('code' => 'SC', 'name' => 'Seychelles'),
			array('code' => 'SL', 'name' => 'Sierra Leone'),
			array('code' => 'SG', 'name' => 'Singapore'),
			array('code' => 'SK', 'name' => 'Slovakia'),
			array('code' => 'SI', 'name' => 'Slovenia'),
			array('code' => 'SB', 'name' => 'Solomon Islands'),
			array('code' => 'SO', 'name' => 'Somalia'),
			array('code' => 'ZA', 'name' => 'South Africa'),
			array('code' => 'GS', 'name' => 'South Georgia South Sandwich Islands'),
			array('code' => 'ES', 'name' => 'Spain'),
			array('code' => 'LK', 'name' => 'Sri Lanka'),
			array('code' => 'SH', 'name' => 'St. Helena'),
			array('code' => 'PM', 'name' => 'St. Pierre and Miquelon'),
			array('code' => 'SD', 'name' => 'Sudan'),
			array('code' => 'SR', 'name' => 'Suriname'),
			array('code' => 'SJ', 'name' => 'Svalbarn and Jan Mayen Islands'),
			array('code' => 'SZ', 'name' => 'Swaziland'),
			array('code' => 'SE', 'name' => 'Sweden'),
			array('code' => 'CH', 'name' => 'Switzerland'),
			array('code' => 'SY', 'name' => 'Syrian Arab Republic'),
			array('code' => 'TW', 'name' => 'Taiwan'),
			array('code' => 'TJ', 'name' => 'Tajikistan'),
			array('code' => 'TZ', 'name' => 'Tanzania, United Republic of'),
			array('code' => 'TH', 'name' => 'Thailand'),
			array('code' => 'TG', 'name' => 'Togo'),
			array('code' => 'TK', 'name' => 'Tokelau'),
			array('code' => 'TO', 'name' => 'Tonga'),
			array('code' => 'TT', 'name' => 'Trinidad and Tobago'),
			array('code' => 'TN', 'name' => 'Tunisia'),
			array('code' => 'TR', 'name' => 'Turkey'),
			array('code' => 'TM', 'name' => 'Turkmenistan'),
			array('code' => 'TC', 'name' => 'Turks and Caicos Islands'),
			array('code' => 'TV', 'name' => 'Tuvalu'),
			array('code' => 'UG', 'name' => 'Uganda'),
			array('code' => 'UA', 'name' => 'Ukraine'),
			array('code' => 'AE', 'name' => 'United Arab Emirates'),
			array('code' => 'GB', 'name' => 'United Kingdom'),
			array('code' => 'UM', 'name' => 'United States minor outlying islands'),
			array('code' => 'UY', 'name' => 'Uruguay'),
			array('code' => 'UZ', 'name' => 'Uzbekistan'),
			array('code' => 'VU', 'name' => 'Vanuatu'),
			array('code' => 'VA', 'name' => 'Vatican City State'),
			array('code' => 'VE', 'name' => 'Venezuela'),
			array('code' => 'VN', 'name' => 'Vietnam'),
			array('code' => 'VG', 'name' => 'Virgin Islands (British)'),
			array('code' => 'VI', 'name' => 'Virgin Islands (U.S.)'),
			array('code' => 'WF', 'name' => 'Wallis and Futuna Islands'),
			array('code' => 'EH', 'name' => 'Western Sahara'),
			array('code' => 'YE', 'name' => 'Yemen'),
			array('code' => 'YU', 'name' => 'Yugoslavia'),
			array('code' => 'ZR', 'name' => 'Zaire'),
			array('code' => 'ZM', 'name' => 'Zambia'),
			array('code' => 'ZW', 'name' => 'Zimbabwe'),
		);

		\DB::table('countries')->insert($countries);

        $country = Country::where('name', 'Bangladesh')->first();

        $divisions = array(
            array('id' => '1', 'country_id' => $country->id, 'name' => 'Chattagram', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '2', 'country_id' => $country->id, 'name' => 'Rajshahi', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '3', 'country_id' => $country->id, 'name' => 'Khulna', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '4', 'country_id' => $country->id, 'name' => 'Barisal', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '5', 'country_id' => $country->id, 'name' => 'Sylhet', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '6', 'country_id' => $country->id, 'name' => 'Dhaka', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '7', 'country_id' => $country->id, 'name' => 'Rangpur', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '8', 'country_id' => $country->id, 'name' => 'Mymensingh', 'created_at' => $date, 'updated_at' => $date),
        );

        $districts = array(
            array('id' => '1', 'division_id' => '1', 'name' => 'Comilla', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '2', 'division_id' => '1', 'name' => 'Feni', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '3', 'division_id' => '1', 'name' => 'Brahmanbaria', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '4', 'division_id' => '1', 'name' => 'Rangamati', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '5', 'division_id' => '1', 'name' => 'Noakhali', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '6', 'division_id' => '1', 'name' => 'Chandpur', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '7', 'division_id' => '1', 'name' => 'Lakshmipur', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '8', 'division_id' => '1', 'name' => 'Chattogram', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '9', 'division_id' => '1', 'name' => 'Coxsbazar', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '10', 'division_id' => '1', 'name' => 'Khagrachhari', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '11', 'division_id' => '1', 'name' => 'Bandarban', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '12', 'division_id' => '2', 'name' => 'Sirajganj', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '13', 'division_id' => '2', 'name' => 'Pabna', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '14', 'division_id' => '2', 'name' => 'Bogura', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '15', 'division_id' => '2', 'name' => 'Rajshahi', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '16', 'division_id' => '2', 'name' => 'Natore', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '17', 'division_id' => '2', 'name' => 'Joypurhat', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '18', 'division_id' => '2', 'name' => 'Chapainawabganj', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '19', 'division_id' => '2', 'name' => 'Naogaon', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '20', 'division_id' => '3', 'name' => 'Jashore', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '21', 'division_id' => '3', 'name' => 'Satkhira', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '22', 'division_id' => '3', 'name' => 'Meherpur', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '23', 'division_id' => '3', 'name' => 'Narail', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '24', 'division_id' => '3', 'name' => 'Chuadanga', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '25', 'division_id' => '3', 'name' => 'Kushtia', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '26', 'division_id' => '3', 'name' => 'Magura', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '27', 'division_id' => '3', 'name' => 'Khulna', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '28', 'division_id' => '3', 'name' => 'Bagerhat', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '29', 'division_id' => '3', 'name' => 'Jhenaidah', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '30', 'division_id' => '4', 'name' => 'Jhalokati Sadar', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '31', 'division_id' => '4', 'name' => 'Patuakhali', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '32', 'division_id' => '4', 'name' => 'Pirojpur', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '33', 'division_id' => '4', 'name' => 'Barisal', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '34', 'division_id' => '4', 'name' => 'Bhola', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '35', 'division_id' => '4', 'name' => 'Barguna', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '36', 'division_id' => '5', 'name' => 'Sylhet', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '37', 'division_id' => '5', 'name' => 'Moulvibazar', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '38', 'division_id' => '5', 'name' => 'Habiganj', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '39', 'division_id' => '5', 'name' => 'Sunamganj', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '40', 'division_id' => '6', 'name' => 'Narsingdi', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '41', 'division_id' => '6', 'name' => 'Gazipur', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '42', 'division_id' => '6', 'name' => 'Shariatpur', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '43', 'division_id' => '6', 'name' => 'Narayanganj', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '44', 'division_id' => '6', 'name' => 'Tangail', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '45', 'division_id' => '6', 'name' => 'Kishoreganj', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '46', 'division_id' => '6', 'name' => 'Manikganj', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '47', 'division_id' => '6', 'name' => 'Dhaka', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '48', 'division_id' => '6', 'name' => 'Munshiganj', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '49', 'division_id' => '6', 'name' => 'Rajbari', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '50', 'division_id' => '6', 'name' => 'Madaripur', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '51', 'division_id' => '6', 'name' => 'Gopalganj', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '52', 'division_id' => '6', 'name' => 'Faridpur', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '53', 'division_id' => '7', 'name' => 'Panchagarh', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '54', 'division_id' => '7', 'name' => 'Dinajpur', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '55', 'division_id' => '7', 'name' => 'Lalmonirhat', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '56', 'division_id' => '7', 'name' => 'Nilphamari', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '57', 'division_id' => '7', 'name' => 'Gaibandha', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '58', 'division_id' => '7', 'name' => 'Thakurgaon', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '59', 'division_id' => '7', 'name' => 'Rangpur', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '60', 'division_id' => '7', 'name' => 'Kurigram', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '61', 'division_id' => '8', 'name' => 'Sherpur', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '62', 'division_id' => '8', 'name' => 'Mymensingh', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '63', 'division_id' => '8', 'name' => 'Jamalpur', 'created_at' => $date, 'updated_at' => $date),
            array('id' => '64', 'division_id' => '8', 'name' => 'Netrokona', 'created_at' => $date, 'updated_at' => $date),
        );

       $upazilas = array (
            array ('id' => 1,'district_id' => 1, 'name' => 'Davidhar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 2,'district_id' => 1, 'name' => 'Barura', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 3,'district_id' => 1, 'name' => 'Brahmanpara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 4,'district_id' => 1, 'name' => 'Chandina', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 5,'district_id' => 1, 'name' => 'Chouddagram', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 6,'district_id' => 1, 'name' => 'Daudkandi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 7,'district_id' => 1, 'name' => 'Homna', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 8,'district_id' => 1, 'name' => 'Laksam', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 9,'district_id' => 1, 'name' => 'Langalkot', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 10,'district_id' => 1, 'name' => 'Muradnagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 11,'district_id' => 1, 'name' => 'Nangalkot', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 12,'district_id' => 1, 'name' => 'Comilla Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 13,'district_id' => 1, 'name' => 'Meghna', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 14,'district_id' => 1, 'name' => 'Monohargonj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 15,'district_id' => 1, 'name' => 'Sadarsouth', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 16,'district_id' => 1, 'name' => 'Titas', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 17,'district_id' => 1, 'name' => 'Burichang', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 18,'district_id' => 1, 'name' => 'Lalmai', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 19,'district_id' => 2, 'name' => 'Chhagalnaiya', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 20,'district_id' => 2, 'name' => 'Feni Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 21,'district_id' => 2, 'name' => 'Sonagazi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 22,'district_id' => 2, 'name' => 'Fulgazi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 23,'district_id' => 2, 'name' => 'Pashurampur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 24,'district_id' => 2, 'name' => 'Daganbhuiyan', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 25,'district_id' => 3, 'name' => 'Brahmanbaria Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 26,'district_id' => 3, 'name' => 'Kasba', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 27,'district_id' => 3, 'name' => 'Nasirnagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 28,'district_id' => 3, 'name' => 'Sarail', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 29,'district_id' => 3, 'name' => 'Ashuganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 30,'district_id' => 3, 'name' => 'Akhaura', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 31,'district_id' => 3, 'name' => 'Nabinagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 32,'district_id' => 3, 'name' => 'Bancharampur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 33,'district_id' => 3, 'name' => 'Bijoynagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 34,'district_id' => 4, 'name' => 'Rangamati Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 35,'district_id' => 4, 'name' => 'Kaptai', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 36,'district_id' => 4, 'name' => 'kaukhali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 37,'district_id' => 4, 'name' => 'Bilaichhari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 38,'district_id' => 4, 'name' => 'Barkal', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 39,'district_id' => 4, 'name' => 'Longachh', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 40,'district_id' => 4, 'name' => 'Marishya', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 41,'district_id' => 4, 'name' => 'Rajsthali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 42,'district_id' => 4, 'name' => 'Belaichari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 43,'district_id' => 4, 'name' => 'Juraichari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 44,'district_id' => 4, 'name' => 'Naniachhar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 45,'district_id' => 4, 'name' => 'Kalampati', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 46,'district_id' => 5, 'name' => 'Noakhali Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 47,'district_id' => 5, 'name' => 'Companiganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 48,'district_id' => 5, 'name' => 'Begumganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 49,'district_id' => 5, 'name' => 'Hatiya', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 50,'district_id' => 5, 'name' => 'Subarnachar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 51,'district_id' => 5, 'name' => 'Kabirhat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 52,'district_id' => 5, 'name' => 'Senbug', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 53,'district_id' => 5, 'name' => 'Chatkhil', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 54,'district_id' => 5, 'name' => 'Sonaimori', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 55,'district_id' => 5, 'name' => 'Basurhat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 56,'district_id' => 6, 'name' => 'Hayemchar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 57,'district_id' => 6, 'name' => 'Kachua', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 58,'district_id' => 6, 'name' => 'Shahrasti', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 59,'district_id' => 6, 'name' => 'Chandpur Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 60,'district_id' => 6, 'name' => 'Matlobganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 61,'district_id' => 6, 'name' => 'Hajiganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 62,'district_id' => 6, 'name' => 'Faridganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 63,'district_id' => 7, 'name' => 'Lakshmipur Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 64,'district_id' => 7, 'name' => 'Char Alexgander', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 65,'district_id' => 7, 'name' => 'Kamalnagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 66,'district_id' => 7, 'name' => 'Raypur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 67,'district_id' => 7, 'name' => 'Ramgati', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 68,'district_id' => 7, 'name' => 'Ramganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 69,'district_id' => 8, 'name' => 'Rangunia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 70,'district_id' => 8, 'name' => 'Sitakunda', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 71,'district_id' => 8, 'name' => 'Mirsharai', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 72,'district_id' => 8, 'name' => 'Patiya', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 73,'district_id' => 8, 'name' => 'Sandwip', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 74,'district_id' => 8, 'name' => 'Banshkhali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 75,'district_id' => 8, 'name' => 'Boalkhali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 76,'district_id' => 8, 'name' => 'Anwara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 77,'district_id' => 8, 'name' => 'Chandanaish', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 78,'district_id' => 8, 'name' => 'Satkania', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 79,'district_id' => 8, 'name' => 'Lohagara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 80,'district_id' => 8, 'name' => 'Hathazari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 81,'district_id' => 8, 'name' => 'Fatikchhari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 82,'district_id' => 8, 'name' => 'Rouzan', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 83,'district_id' => 8, 'name' => 'Karnafuli', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 84,'district_id' => 8, 'name' => 'Chattogram Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 85,'district_id' => 8, 'name' => 'East Joara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 86,'district_id' => 8, 'name' => 'Jaldi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 87,'district_id' => 9, 'name' => 'Coxsbazar Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 88,'district_id' => 9, 'name' => 'Chiringga', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 89,'district_id' => 9, 'name' => 'Gorakghat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 90,'district_id' => 9, 'name' => 'Kutubdia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 91,'district_id' => 9, 'name' => 'Ukhiya', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 92,'district_id' => 9, 'name' => 'Moheshkhali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 93,'district_id' => 9, 'name' => 'Pekua', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 94,'district_id' => 9, 'name' => 'Ramu', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 95,'district_id' => 9, 'name' => 'Teknaf', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 96,'district_id' => 10, 'name' => 'Khagrachari Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 97,'district_id' => 10, 'name' => 'Dighinala', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 98,'district_id' => 10, 'name' => 'Panchhari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 99,'district_id' => 10, 'name' => 'Laxmichhari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 100,'district_id' => 10, 'name' => 'Mohalchhari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 101,'district_id' => 10, 'name' => 'Manikchhari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 102,'district_id' => 10, 'name' => 'Ramgarh', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 103,'district_id' => 10, 'name' => 'Matiranga', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 104,'district_id' => 10, 'name' => 'Guimara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 105,'district_id' => 11, 'name' => 'Bandarban Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 106,'district_id' => 11, 'name' => 'Alikadam', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 107,'district_id' => 11, 'name' => 'Naikhong', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 108,'district_id' => 11, 'name' => 'Roanchhari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 109,'district_id' => 11, 'name' => 'Lama', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 110,'district_id' => 11, 'name' => 'Ruma', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 111,'district_id' => 11, 'name' => 'Thanchi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 112,'district_id' => 12, 'name' => 'Belkuchi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 113,'district_id' => 12, 'name' => 'Dhangora', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 114,'district_id' => 12, 'name' => 'Chauhali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 115,'district_id' => 12, 'name' => 'Kamarkhand', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 116,'district_id' => 12, 'name' => 'Kazipur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 117,'district_id' => 12, 'name' => 'Raigonj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 118,'district_id' => 12, 'name' => 'Shahjadpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 119,'district_id' => 12, 'name' => 'Sirajganj Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 120,'district_id' => 12, 'name' => 'Tarash', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 121,'district_id' => 12, 'name' => 'Ullapara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 122,'district_id' => 13, 'name' => 'Sujanagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 123,'district_id' => 13, 'name' => 'Ishwardi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 124,'district_id' => 13, 'name' => 'Bhangura', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 125,'district_id' => 13, 'name' => 'Pabna Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 126,'district_id' => 13, 'name' => 'Banwarinagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 127,'district_id' => 13, 'name' => 'Bera', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 128,'district_id' => 13, 'name' => 'Atghoria', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 129,'district_id' => 13, 'name' => 'Chatmohar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 130,'district_id' => 13, 'name' => 'Debottar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 131,'district_id' => 13, 'name' => 'Sathia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 132,'district_id' => 14, 'name' => 'Kahaloo', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 133,'district_id' => 14, 'name' => 'Bogra Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 134,'district_id' => 14, 'name' => 'Shariakandi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 135,'district_id' => 14, 'name' => 'Shajahanpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 136,'district_id' => 14, 'name' => 'Dupchanchia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 137,'district_id' => 14, 'name' => 'Adamdighi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 138,'district_id' => 14, 'name' => 'Nondigram', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 139,'district_id' => 14, 'name' => 'Sonatala', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 140,'district_id' => 14, 'name' => 'Dhunot', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 141,'district_id' => 14, 'name' => 'Gabtali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 142,'district_id' => 14, 'name' => 'Sherpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 143,'district_id' => 14, 'name' => 'Shibganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 144,'district_id' => 15, 'name' => 'Paba', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 145,'district_id' => 15, 'name' => 'Durgapur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 146,'district_id' => 15, 'name' => 'Mohonpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 147,'district_id' => 15, 'name' => 'Charghat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 148,'district_id' => 15, 'name' => 'Puthia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 149,'district_id' => 15, 'name' => 'Rajshahi Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 150,'district_id' => 15, 'name' => 'Bagha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 151,'district_id' => 15, 'name' => 'Godagari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 152,'district_id' => 15, 'name' => 'Bhabaniganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 153,'district_id' => 15, 'name' => 'Tanore', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 154,'district_id' => 15, 'name' => 'Bagmara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 155,'district_id' => 15, 'name' => 'Lalitganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 156,'district_id' => 16, 'name' => 'Natore Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 157,'district_id' => 16, 'name' => 'Singra', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 158,'district_id' => 16, 'name' => 'Baraigram', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 159,'district_id' => 16, 'name' => 'Bagatipara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 160,'district_id' => 16, 'name' => 'Lalpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 161,'district_id' => 16, 'name' => 'Gurudaspur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 162,'district_id' => 16, 'name' => 'Naldanga', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 163,'district_id' => 16, 'name' => 'Gopalpur UPO', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 164,'district_id' => 16, 'name' => 'Harua', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 165,'district_id' => 16, 'name' => 'Hatgurudaspur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 166,'district_id' => 16, 'name' => 'Laxman', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 167,'district_id' => 17, 'name' => 'Akkelpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 168,'district_id' => 17, 'name' => 'Kalai', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 169,'district_id' => 17, 'name' => 'Khetlal', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 170,'district_id' => 17, 'name' => 'Panchbibi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 171,'district_id' => 17, 'name' => 'Joypurhat Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 172,'district_id' => 18, 'name' => 'Chapainawabganj Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 173,'district_id' => 18, 'name' => 'Gomostapur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 174,'district_id' => 18, 'name' => 'Nachol', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 175,'district_id' => 18, 'name' => 'Rohanpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 176,'district_id' => 18, 'name' => 'Bholahat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 177,'district_id' => 18, 'name' => 'Shibganj U.P.O', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 178,'district_id' => 19, 'name' => 'Mohadevpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 179,'district_id' => 19, 'name' => 'Badalgachi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 180,'district_id' => 19, 'name' => 'Patnitala', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 181,'district_id' => 19, 'name' => 'Dhamoirhat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 182,'district_id' => 19, 'name' => 'Niamatpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 183,'district_id' => 19, 'name' => 'Nitpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 184,'district_id' => 19, 'name' => 'Ahsanganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 185,'district_id' => 19, 'name' => 'Manda', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 186,'district_id' => 19, 'name' => 'Atrai', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 187,'district_id' => 19, 'name' => 'Raninagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 188,'district_id' => 19, 'name' => 'Naogaon Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 189,'district_id' => 19, 'name' => 'Porsha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 190,'district_id' => 19, 'name' => 'Sapahar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 191,'district_id' => 20, 'name' => 'Manirampur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 192,'district_id' => 20, 'name' => 'Noapara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 193,'district_id' => 20, 'name' => 'Abhaynagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 194,'district_id' => 20, 'name' => 'Bagherpara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 195,'district_id' => 20, 'name' => 'Chougachha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 196,'district_id' => 20, 'name' => 'Jhikargacha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 197,'district_id' => 20, 'name' => 'Keshabpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 198,'district_id' => 20, 'name' => 'Jessore Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 199,'district_id' => 20, 'name' => 'Sharsha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 200,'district_id' => 21, 'name' => 'Assasuni', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 201,'district_id' => 21, 'name' => 'Debhata', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 202,'district_id' => 21, 'name' => 'Kalaroa', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 203,'district_id' => 21, 'name' => 'Satkhira Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 204,'district_id' => 21, 'name' => 'Shyamnagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 205,'district_id' => 21, 'name' => 'Tala', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 206,'district_id' => 21, 'name' => 'Kaliganj UPO', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 207,'district_id' => 21, 'name' => 'Nakipur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 208,'district_id' => 22, 'name' => 'Mujibnagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 209,'district_id' => 22, 'name' => 'Meherpur Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 210,'district_id' => 22, 'name' => 'Gangni', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 211,'district_id' => 23, 'name' => 'Narail Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 212,'district_id' => 23, 'name' => 'Lohagara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 213,'district_id' => 23, 'name' => 'Kalia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 214,'district_id' => 23, 'name' => 'Laxmipasha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 215,'district_id' => 23, 'name' => 'Mohajan', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 216,'district_id' => 24, 'name' => 'Chuadanga Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 217,'district_id' => 24, 'name' => 'Alamdanga', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 218,'district_id' => 24, 'name' => 'Damurhuda', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 219,'district_id' => 24, 'name' => 'Doulatganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 220,'district_id' => 24, 'name' => 'Jibannagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 221,'district_id' => 25, 'name' => 'Kushtia Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 222,'district_id' => 25, 'name' => 'Rafayetpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 223,'district_id' => 25, 'name' => 'Kumarkhali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 224,'district_id' => 25, 'name' => 'Khoksa', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 225,'district_id' => 25, 'name' => 'Mirpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 226,'district_id' => 25, 'name' => 'Daulatpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 227,'district_id' => 25, 'name' => 'Bheramara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 228,'district_id' => 25, 'name' => 'Janipur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 229,'district_id' => 26, 'name' => 'Shalikha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 230,'district_id' => 26, 'name' => 'Sreepur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 231,'district_id' => 26, 'name' => 'Sripur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 232,'district_id' => 26, 'name' => 'Magura Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 233,'district_id' => 26, 'name' => 'Arpara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 234,'district_id' => 26, 'name' => 'Mohammadpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 235,'district_id' => 26, 'name' => 'Shripur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 236,'district_id' => 27, 'name' => 'Paikgasa', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 237,'district_id' => 27, 'name' => 'Fultola', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 238,'district_id' => 27, 'name' => 'Sajiara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 239,'district_id' => 27, 'name' => 'Alaipur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 240,'district_id' => 27, 'name' => 'Digholia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 241,'district_id' => 27, 'name' => 'Khulna Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 242,'district_id' => 27, 'name' => 'Madinabad', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 243,'district_id' => 27, 'name' => 'Rupsha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 244,'district_id' => 27, 'name' => 'Terokhada', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 245,'district_id' => 27, 'name' => 'Dumuria', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 246,'district_id' => 27, 'name' => 'Botiaghata', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 247,'district_id' => 27, 'name' => 'Chalna Bazar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 248,'district_id' => 27, 'name' => 'Dakop', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 249,'district_id' => 27, 'name' => 'Koyra', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 250,'district_id' => 28, 'name' => 'Fakirhat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 251,'district_id' => 28, 'name' => 'Bagerhat Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 252,'district_id' => 28, 'name' => 'Mollahat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 253,'district_id' => 28, 'name' => 'Sarankhola', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 254,'district_id' => 28, 'name' => 'Rampal', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 255,'district_id' => 28, 'name' => 'Rayenda', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 256,'district_id' => 28, 'name' => 'Morrelganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 257,'district_id' => 28, 'name' => 'Kachua UPO', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 258,'district_id' => 28, 'name' => 'Mongla', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 259,'district_id' => 28, 'name' => 'Chitalmari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 260,'district_id' => 28, 'name' => 'Chalna Ankorage', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 261,'district_id' => 29, 'name' => 'Jhenaidah Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 262,'district_id' => 29, 'name' => 'Shailkupa', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 263,'district_id' => 29, 'name' => 'Harinakundu', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 264,'district_id' => 29, 'name' => 'Kaliganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 265,'district_id' => 29, 'name' => 'Kotchandpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 266,'district_id' => 29, 'name' => 'Moheshpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 267,'district_id' => 30, 'name' => 'Jhalokati Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 268,'district_id' => 30, 'name' => 'Kathalia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 269,'district_id' => 30, 'name' => 'Nalchity', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 270,'district_id' => 30, 'name' => 'Rajapur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 271,'district_id' => 31, 'name' => 'Bauphal', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 272,'district_id' => 31, 'name' => 'Patuakhali Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 273,'district_id' => 31, 'name' => 'Dumki', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 274,'district_id' => 31, 'name' => 'Dashmina', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 275,'district_id' => 31, 'name' => 'Kalapara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 276,'district_id' => 31, 'name' => 'Mirzaganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 277,'district_id' => 31, 'name' => 'Galachipa', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 278,'district_id' => 31, 'name' => 'Rangabali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 279,'district_id' => 31, 'name' => 'Khepupara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 280,'district_id' => 31, 'name' => 'Subidkhali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 281,'district_id' => 32, 'name' => 'Pirojpur Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 282,'district_id' => 32, 'name' => 'Nazirpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 283,'district_id' => 32, 'name' => 'Kawkhali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 284,'district_id' => 32, 'name' => 'Zianagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 285,'district_id' => 32, 'name' => 'Bhandaria', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 286,'district_id' => 32, 'name' => 'Mathbaria', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 287,'district_id' => 32, 'name' => 'Nesarabad', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 288,'district_id' => 32, 'name' => 'Swarupkathi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 289,'district_id' => 33, 'name' => 'Barisal Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 290,'district_id' => 33, 'name' => 'Bakerganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 291,'district_id' => 33, 'name' => 'Babuganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 292,'district_id' => 33, 'name' => 'Wazirpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 293,'district_id' => 33, 'name' => 'Banaripara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 294,'district_id' => 33, 'name' => 'Gournadi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 295,'district_id' => 33, 'name' => 'Agailjhara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 296,'district_id' => 33, 'name' => 'Barajalia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 297,'district_id' => 33, 'name' => 'Mehendiganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 298,'district_id' => 33, 'name' => 'Sahebganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 299,'district_id' => 33, 'name' => 'Uazirpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 300,'district_id' => 33, 'name' => 'Muladi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 301,'district_id' => 33, 'name' => 'Hizla', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 302,'district_id' => 34, 'name' => 'Bhola Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 303,'district_id' => 34, 'name' => 'Borhanuddin UPO', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 304,'district_id' => 34, 'name' => 'Charfashion', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 305,'district_id' => 34, 'name' => 'Doulatkhan', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 306,'district_id' => 34, 'name' => 'Monpura', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 307,'district_id' => 34, 'name' => 'Tazumuddin', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 308,'district_id' => 34, 'name' => 'Lalmohan UPO', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 309,'district_id' => 34, 'name' => 'Hajirhat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 310,'district_id' => 34, 'name' => 'Hatshoshiganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 311,'district_id' => 35, 'name' => 'Amtali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 312,'district_id' => 35, 'name' => 'Barguna Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 313,'district_id' => 35, 'name' => 'Betagi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 314,'district_id' => 35, 'name' => 'Bamna', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 315,'district_id' => 35, 'name' => 'Patharghata', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 316,'district_id' => 35, 'name' => 'Taltali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 317,'district_id' => 36, 'name' => 'Balaganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 318,'district_id' => 36, 'name' => 'Bianibazar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 319,'district_id' => 36, 'name' => 'Bishwanath', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 320,'district_id' => 36, 'name' => 'Companiganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 321,'district_id' => 36, 'name' => 'Fenchuganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 322,'district_id' => 36, 'name' => 'Golapganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 323,'district_id' => 36, 'name' => 'Gowainghat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 324,'district_id' => 36, 'name' => 'Jaintiapur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 325,'district_id' => 36, 'name' => 'Jakiganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 326,'district_id' => 36, 'name' => 'Kanaighat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 327,'district_id' => 36, 'name' => 'Sylhet Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 328,'district_id' => 36, 'name' => 'Zakiganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 329,'district_id' => 36, 'name' => 'Dakshinsurma', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 330,'district_id' => 36, 'name' => 'Osmaninagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 331,'district_id' => 37, 'name' => 'Barlekha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 332,'district_id' => 37, 'name' => 'Kamolganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 333,'district_id' => 37, 'name' => 'Kulaura', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 334,'district_id' => 37, 'name' => 'Moulvibazar Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 335,'district_id' => 37, 'name' => 'Rajnagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 336,'district_id' => 37, 'name' => 'Sreemangal', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 337,'district_id' => 37, 'name' => 'Juri', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 338,'district_id' => 38, 'name' => 'Nabiganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 339,'district_id' => 38, 'name' => 'Bahubal', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 340,'district_id' => 38, 'name' => 'Ajmiriganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 341,'district_id' => 38, 'name' => 'Baniachong', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 342,'district_id' => 38, 'name' => 'Lakhai', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 343,'district_id' => 38, 'name' => 'Chunarughat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 344,'district_id' => 38, 'name' => 'Habiganj Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 345,'district_id' => 38, 'name' => 'Kalauk', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 346,'district_id' => 38, 'name' => 'Madhabpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 347,'district_id' => 39, 'name' => 'Sunamganj Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 348,'district_id' => 39, 'name' => 'South Sunamganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 349,'district_id' => 39, 'name' => 'Bishwambarpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 350,'district_id' => 39, 'name' => 'Chhatak', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 351,'district_id' => 39, 'name' => 'Jagannathpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 352,'district_id' => 39, 'name' => 'Sachna', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 353,'district_id' => 39, 'name' => 'Dowarabazar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 354,'district_id' => 39, 'name' => 'Ghungiar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 355,'district_id' => 39, 'name' => 'Tahirpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 356,'district_id' => 39, 'name' => 'Dharmapasha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 357,'district_id' => 39, 'name' => 'Jamalganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 358,'district_id' => 39, 'name' => 'Shalla', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 359,'district_id' => 39, 'name' => 'Dhirai Chandpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 360,'district_id' => 40, 'name' => 'Belabo', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 361,'district_id' => 40, 'name' => 'Monohardi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 362,'district_id' => 40, 'name' => 'Narsingdi Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 363,'district_id' => 40, 'name' => 'Palash', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 364,'district_id' => 40, 'name' => 'Raipura', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 365,'district_id' => 40, 'name' => 'Shibpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 366,'district_id' => 41, 'name' => 'Kaliganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 367,'district_id' => 41, 'name' => 'Kaliakair', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 368,'district_id' => 41, 'name' => 'Kapashia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 369,'district_id' => 41, 'name' => 'Monnunagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 370,'district_id' => 41, 'name' => 'Gazipur Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 371,'district_id' => 41, 'name' => 'Sreepur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 372,'district_id' => 42, 'name' => 'Shariatpur Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 373,'district_id' => 42, 'name' => 'Naria', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 374,'district_id' => 42, 'name' => 'Zajira', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 375,'district_id' => 42, 'name' => 'Gosairhat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 376,'district_id' => 42, 'name' => 'Bhedarganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 377,'district_id' => 42, 'name' => 'Damudya', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 378,'district_id' => 43, 'name' => 'Araihazar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 379,'district_id' => 43, 'name' => 'Bandar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 380,'district_id' => 43, 'name' => 'Baidder Bazar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 381,'district_id' => 43, 'name' => 'Fatullah', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 382,'district_id' => 43, 'name' => 'Siddirganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 383,'district_id' => 43, 'name' => 'Narayanganj Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 384,'district_id' => 43, 'name' => 'Rupganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 385,'district_id' => 43, 'name' => 'Sonargaon', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 386,'district_id' => 44, 'name' => 'Basail', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 387,'district_id' => 44, 'name' => 'Kashkaolia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 388,'district_id' => 44, 'name' => 'Bhuapur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 389,'district_id' => 44, 'name' => 'Delduar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 390,'district_id' => 44, 'name' => 'Ghatail', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 391,'district_id' => 44, 'name' => 'Gopalpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 392,'district_id' => 44, 'name' => 'Madhupur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 393,'district_id' => 44, 'name' => 'Mirzapur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 394,'district_id' => 44, 'name' => 'Nagarpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 395,'district_id' => 44, 'name' => 'Sakhipur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 396,'district_id' => 44, 'name' => 'Tangail Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 397,'district_id' => 44, 'name' => 'Kalihati', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 398,'district_id' => 44, 'name' => 'Dhanbari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 399,'district_id' => 45, 'name' => 'Itna', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 400,'district_id' => 45, 'name' => 'Katiadi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 401,'district_id' => 45, 'name' => 'Bhairob', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 402,'district_id' => 45, 'name' => 'Tarail', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 403,'district_id' => 45, 'name' => 'Hossainpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 404,'district_id' => 45, 'name' => 'Pakundia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 405,'district_id' => 45, 'name' => 'Kuliarchar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 406,'district_id' => 45, 'name' => 'Kishoreganj Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 407,'district_id' => 45, 'name' => 'Karimganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 408,'district_id' => 45, 'name' => 'Bajitpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 409,'district_id' => 45, 'name' => 'Austagram', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 410,'district_id' => 45, 'name' => 'Mithamoin', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 411,'district_id' => 45, 'name' => 'Nikli', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 412,'district_id' => 46, 'name' => 'Harirampur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 413,'district_id' => 46, 'name' => 'Saturia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 414,'district_id' => 46, 'name' => 'Manikganj Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 415,'district_id' => 46, 'name' => 'Ghior', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 416,'district_id' => 46, 'name' => 'Lechhraganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 417,'district_id' => 46, 'name' => 'Shibaloy', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 418,'district_id' => 46, 'name' => 'Doulatpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 419,'district_id' => 46, 'name' => 'Singari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 420,'district_id' => 47, 'name' => 'Savar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 421,'district_id' => 47, 'name' => 'Dhamrai', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 422,'district_id' => 47, 'name' => 'Demra', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 423,'district_id' => 47, 'name' => 'Dhanmondi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 424,'district_id' => 47, 'name' => 'Dhaka Cantt.', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 425,'district_id' => 47, 'name' => 'Gulshan', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 426,'district_id' => 47, 'name' => 'Jatrabari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 427,'district_id' => 47, 'name' => 'Joypara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 428,'district_id' => 47, 'name' => 'Khilgaon', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 429,'district_id' => 47, 'name' => 'Khilkhet', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 430,'district_id' => 47, 'name' => 'Lalbagh', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 431,'district_id' => 47, 'name' => 'Mirpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 432,'district_id' => 47, 'name' => 'Mohammadpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 433,'district_id' => 47, 'name' => 'Motijheel', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 434,'district_id' => 47, 'name' => 'New Market', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 435,'district_id' => 47, 'name' => 'Paltan', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 436,'district_id' => 47, 'name' => 'Ramna', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 437,'district_id' => 47, 'name' => 'Sabujbag', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 438,'district_id' => 47, 'name' => 'Sutrapur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 439,'district_id' => 47, 'name' => 'Tejgaon', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 440,'district_id' => 47, 'name' => 'Tejgaon Industrial Area', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 441,'district_id' => 47, 'name' => 'Uttara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 442,'district_id' => 47, 'name' => 'Keraniganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 443,'district_id' => 47, 'name' => 'Nawabganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 444,'district_id' => 47, 'name' => 'Dohar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 445,'district_id' => 48, 'name' => 'Munshiganj Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 446,'district_id' => 48, 'name' => 'Sreenagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 447,'district_id' => 48, 'name' => 'Sirajdikhan', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 448,'district_id' => 48, 'name' => 'Louhajanj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 449,'district_id' => 48, 'name' => 'Gajaria', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 450,'district_id' => 48, 'name' => 'Tongibari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 451,'district_id' => 49, 'name' => 'Rajbari Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 452,'district_id' => 49, 'name' => 'Goalanda', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 453,'district_id' => 49, 'name' => 'Pangsha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 454,'district_id' => 49, 'name' => 'Baliakandi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 455,'district_id' => 49, 'name' => 'Kalukhali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 456,'district_id' => 50, 'name' => 'Madaripur Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 457,'district_id' => 50, 'name' => 'Shibchar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 458,'district_id' => 50, 'name' => 'Kalkini', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 459,'district_id' => 50, 'name' => 'Barhamganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 460,'district_id' => 50, 'name' => 'Rajoir', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 461,'district_id' => 51, 'name' => 'Gopalganj Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 462,'district_id' => 51, 'name' => 'Kashiani', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 463,'district_id' => 51, 'name' => 'Tungipara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 464,'district_id' => 51, 'name' => 'Kotalipara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 465,'district_id' => 51, 'name' => 'Maksudpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 466,'district_id' => 52, 'name' => 'Faridpur Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 467,'district_id' => 52, 'name' => 'Alfadanga', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 468,'district_id' => 52, 'name' => 'Boalmari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 469,'district_id' => 52, 'name' => 'Sadarpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 470,'district_id' => 52, 'name' => 'Nagarkanda', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 471,'district_id' => 52, 'name' => 'Bhanga', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 472,'district_id' => 52, 'name' => 'Charbhadrasan', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 473,'district_id' => 52, 'name' => 'Madhukhali', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 474,'district_id' => 52, 'name' => 'Shriangan', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 475,'district_id' => 52, 'name' => 'Saltha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 476,'district_id' => 53, 'name' => 'Panchagarh Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 477,'district_id' => 53, 'name' => 'Debiganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 478,'district_id' => 53, 'name' => 'Boda', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 479,'district_id' => 53, 'name' => 'Chotto Dab', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 480,'district_id' => 53, 'name' => 'Atwari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 481,'district_id' => 53, 'name' => 'Tetulia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 482,'district_id' => 54, 'name' => 'Nawabganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 483,'district_id' => 54, 'name' => 'Birganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 484,'district_id' => 54, 'name' => 'Ghoraghat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 485,'district_id' => 54, 'name' => 'Birampur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 486,'district_id' => 54, 'name' => 'Bangla Hili', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 487,'district_id' => 54, 'name' => 'Parbatipur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 488,'district_id' => 54, 'name' => 'Setabganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 489,'district_id' => 54, 'name' => 'Bochaganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 490,'district_id' => 54, 'name' => 'Kaharol', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 491,'district_id' => 54, 'name' => 'Fulbari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 492,'district_id' => 54, 'name' => 'Dinajpur Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 493,'district_id' => 54, 'name' => 'Hakimpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 494,'district_id' => 54, 'name' => 'Khansama', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 495,'district_id' => 54, 'name' => 'Maharajganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 496,'district_id' => 54, 'name' => 'Birol', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 497,'district_id' => 54, 'name' => 'Chirirbandar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 498,'district_id' => 55, 'name' => 'Lalmonirhat Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 499,'district_id' => 55, 'name' => 'Kaliganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 500,'district_id' => 55, 'name' => 'Hatibandha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 501,'district_id' => 55, 'name' => 'Patgram', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 502,'district_id' => 55, 'name' => 'Tushbhandar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 503,'district_id' => 55, 'name' => 'Aditmari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 504,'district_id' => 56, 'name' => 'Syedpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 505,'district_id' => 56, 'name' => 'Domar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 506,'district_id' => 56, 'name' => 'Dimla', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 507,'district_id' => 56, 'name' => 'Jaldhaka', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 508,'district_id' => 56, 'name' => 'Kishorganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 509,'district_id' => 56, 'name' => 'Nilphamari Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 510,'district_id' => 57, 'name' => 'Sadullapur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 511,'district_id' => 57, 'name' => 'Gaibandha Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 512,'district_id' => 57, 'name' => 'Bonarpara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 513,'district_id' => 57, 'name' => 'Palashbari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 514,'district_id' => 57, 'name' => 'Saghata', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 515,'district_id' => 57, 'name' => 'Gobindaganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 516,'district_id' => 57, 'name' => 'Sundarganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 517,'district_id' => 57, 'name' => 'Phulchari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 518,'district_id' => 58, 'name' => 'Thakurgaon Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 519,'district_id' => 58, 'name' => 'Pirganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 520,'district_id' => 58, 'name' => 'Ranisankail', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 521,'district_id' => 58, 'name' => 'Haripur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 522,'district_id' => 58, 'name' => 'Baliadangi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 523,'district_id' => 58, 'name' => 'Jibanpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 524,'district_id' => 59, 'name' => 'Rangpur Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 525,'district_id' => 59, 'name' => 'Gangachara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 526,'district_id' => 59, 'name' => 'Taragonj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 527,'district_id' => 59, 'name' => 'Badargonj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 528,'district_id' => 59, 'name' => 'Mithapukur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 529,'district_id' => 59, 'name' => 'Pirgonj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 530,'district_id' => 59, 'name' => 'Kaunia', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 531,'district_id' => 59, 'name' => 'Pirgacha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 532,'district_id' => 60, 'name' => 'Kurigram Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 533,'district_id' => 60, 'name' => 'Rajibpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 534,'district_id' => 60, 'name' => 'Nageshwari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 535,'district_id' => 60, 'name' => 'Bhurungamari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 536,'district_id' => 60, 'name' => 'Phulbari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 537,'district_id' => 60, 'name' => 'Rajarhat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 538,'district_id' => 60, 'name' => 'Ulipur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 539,'district_id' => 60, 'name' => 'Chilmari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 540,'district_id' => 60, 'name' => 'Rowmari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 541,'district_id' => 60, 'name' => 'Charrajibpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 542,'district_id' => 61, 'name' => 'Sherpur Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 543,'district_id' => 61, 'name' => 'Nalitabari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 544,'district_id' => 61, 'name' => 'Sreebordi', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 545,'district_id' => 61, 'name' => 'Nokla', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 546,'district_id' => 61, 'name' => 'Jhenaigati', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 547,'district_id' => 61, 'name' => 'Bakshigonj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 548,'district_id' => 62, 'name' => 'Fulbaria', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 549,'district_id' => 62, 'name' => 'Trishal', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 550,'district_id' => 62, 'name' => 'Bhaluka', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 551,'district_id' => 62, 'name' => 'Muktagachha', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 552,'district_id' => 62, 'name' => 'Mymensingh Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 553,'district_id' => 62, 'name' => 'Dhobaura', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 554,'district_id' => 62, 'name' => 'Phulpur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 555,'district_id' => 62, 'name' => 'Haluaghat', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 556,'district_id' => 62, 'name' => 'Gouripur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 557,'district_id' => 62, 'name' => 'Gafargaon', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 558,'district_id' => 62, 'name' => 'Iswarganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 559,'district_id' => 62, 'name' => 'Nandail', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 560,'district_id' => 62, 'name' => 'Tarakanda', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 561,'district_id' => 63, 'name' => 'Jamalpur Sadar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 562,'district_id' => 63, 'name' => 'Melandah', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 563,'district_id' => 63, 'name' => 'Islampur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 564,'district_id' => 63, 'name' => 'Dewangonj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 565,'district_id' => 63, 'name' => 'Sarishabari', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 566,'district_id' => 63, 'name' => 'Madarganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 567,'district_id' => 63, 'name' => 'Bokshiganj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 568,'district_id' => 64, 'name' => 'Barhatta', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 569,'district_id' => 64, 'name' => 'Durgapur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 570,'district_id' => 64, 'name' => 'Kendua', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 571,'district_id' => 64, 'name' => 'Atpara', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 572,'district_id' => 64, 'name' => 'Susang Durgapur', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 573,'district_id' => 64, 'name' => 'Madan', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 574,'district_id' => 64, 'name' => 'Moddhynagar', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 575,'district_id' => 64, 'name' => 'Khaliajuri', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 576,'district_id' => 64, 'name' => 'Kalmakanda', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 577,'district_id' => 64, 'name' => 'Mohongonj', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 578,'district_id' => 64, 'name' => 'Purbadhala', 'created_at' => $date, 'updated_at' => $date),
            array ('id' => 579,'district_id' => 64, 'name' => 'Netrokona Sadar', 'created_at' => $date, 'updated_at' => $date),
        );

        Division::insert($divisions);
        District::insert($districts);
        Upazila::insert($upazilas);
    }
}
